title: The Place
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6845878
  brandStrength: 0.5
  lightness: 0.5071685
  brandColors:
    - '#ffffff'
    - '#0d1c1f'
    - '#cacac2'
    - '#7b6f59'
    - '#fb8b37'
  rhythmicContrast: 0.4731183
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: The Place
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4050179
layout_spectrum: 0.7240143
