name: The Place
favicon: null
layout_spectrum: 1
typography_spectrum: 0.22092
title: The Place
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010000'
    - '#4a4c50'
    - '#83858a'
    - '#ea5358'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
