name: The Place
favicon: null
layout_spectrum: 0.01271
typography_spectrum: 0.77224
title: The Place
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0d1c1f'
    - '#cacac2'
    - '#7b6f59'
    - '#fb8b37'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0
purpose: []
